version: 2

jobs:
  build:
    steps:
      - run
dependencies:
    override:
        - sudo pip install awscli
-deployment:
  prod:
    branch: master
    commands:
      - aws s3 sync /home/ubuntu/test-bucket-ci2000 s3://s3awscd --delete


# version: 2
# jobs:
#   build:
#
# workflows:
#   version: 2
#   build_and_test:
#     jobs:

# dependencies:
#     override:
#         - sudo pip install awscli
# deployment:
#   prod:
#     branch: master
#     commands:
#       - aws s3 sync /home/ubuntu/test-bucket-ci2000 s3://s3awscd --delete
